apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: miniapp
build:
  artifacts:
    - image: muhammadzain12/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: muhammadzain12/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./*.js"
            dest: .
    - image: muhammadzain12/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./*.js"
            dest: .
    - image: muhammadzain12/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./*.js"
            dest: .
    - image: muhammadzain12/query
      context: query-service
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "./*.js"
            dest: .
manifests:
  rawYaml:
  - ./infra/k8s/*