apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: posts:latest
          resources:
            limits:
              memory: "200Mi"
              cpu: "0.6"
            requests:
              memory: "100Mi"
              cpu: "0.3"
